#!/usr/bin/env node

/**
 * Session Capture Tool
 *
 * Opens a headed browser for manual login, then captures and persists
 * the session. The browser profile is shared with connectors of the
 * same platform name, so subsequent test runs automatically have the session.
 *
 * Usage:
 *   node capture-session.cjs <platform> <login-url> [options]
 *
 * Examples:
 *   node capture-session.cjs google https://accounts.google.com
 *   node capture-session.cjs uber https://auth.uber.com/v2
 *   node capture-session.cjs google https://accounts.google.com --timeout 300
 *
 * Options:
 *   --timeout <seconds>   Max wait time for login (default: 300 = 5 minutes)
 *   --check-url <pattern> URL substring that indicates successful login
 */

const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');
const os = require('os');

// ─── ANSI Colors ────────────────────────────────────────────
const c = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  gray: '\x1b[90m',
};

function print(color, prefix, msg) {
  const ts = new Date().toLocaleTimeString('en-US', { hour12: false });
  console.log(`${c.gray}${ts}${c.reset} ${color}${prefix}${c.reset} ${msg}`);
}

// ─── Resolve Playwright Runner ──────────────────────────────
function resolveRunnerDir() {
  if (process.env.PLAYWRIGHT_RUNNER_DIR) {
    const dir = process.env.PLAYWRIGHT_RUNNER_DIR;
    if (fs.existsSync(path.join(dir, 'index.cjs'))) return dir;
    console.error(`${c.red}PLAYWRIGHT_RUNNER_DIR set but index.cjs not found in: ${dir}${c.reset}`);
    process.exit(1);
  }

  const candidates = [
    path.resolve(__dirname, '..', 'data-dt-app', 'playwright-runner'),
    path.join(os.homedir(), 'Documents', 'GitHub', 'data-dt-app', 'playwright-runner'),
    path.join(os.homedir(), 'Documents', 'Github', 'data-dt-app', 'playwright-runner'),
    path.join(os.homedir(), 'code', 'data-dt-app', 'playwright-runner'),
    path.join(os.homedir(), 'src', 'data-dt-app', 'playwright-runner'),
  ];

  for (const dir of candidates) {
    if (fs.existsSync(path.join(dir, 'index.cjs'))) return dir;
  }

  console.error(`${c.red}Could not find playwright-runner. Set PLAYWRIGHT_RUNNER_DIR env var.${c.reset}`);
  process.exit(1);
}

// ─── CLI Argument Parsing ───────────────────────────────────
function parseArgs() {
  const args = process.argv.slice(2);
  const parsed = {
    platform: null,
    loginUrl: null,
    timeout: 300,
    checkUrl: null,
  };

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--timeout' && args[i + 1]) {
      parsed.timeout = parseInt(args[++i], 10);
    } else if (args[i] === '--check-url' && args[i + 1]) {
      parsed.checkUrl = args[++i];
    } else if (args[i] === '--help' || args[i] === '-h') {
      printUsage();
      process.exit(0);
    } else if (!args[i].startsWith('--')) {
      if (!parsed.platform) parsed.platform = args[i];
      else if (!parsed.loginUrl) parsed.loginUrl = args[i];
    }
  }

  if (!parsed.platform || !parsed.loginUrl) {
    printUsage();
    process.exit(1);
  }

  return parsed;
}

function printUsage() {
  console.log(`
${c.bold}Session Capture Tool${c.reset}

${c.cyan}Usage:${c.reset}
  node capture-session.cjs <platform> <login-url> [options]

${c.cyan}Options:${c.reset}
  --timeout <seconds>     Max wait time for login (default: 300)
  --check-url <pattern>   URL substring indicating successful login
  --help, -h              Show this help

${c.cyan}Examples:${c.reset}
  node capture-session.cjs google https://accounts.google.com
  node capture-session.cjs uber https://auth.uber.com/v2
  node capture-session.cjs google https://accounts.google.com --check-url myaccount.google.com

${c.cyan}How it works:${c.reset}
  1. Opens a headed browser at the login URL
  2. You log in manually (handles CAPTCHAs, 2FA, OAuth, etc.)
  3. Login is detected automatically (URL change + cookie increase)
  4. Session is persisted in browser profile for connector reuse

${c.cyan}Profile sharing:${c.reset}
  The browser profile is stored at ~/.dataconnect/browser-profiles/<platform>-playwright/
  Any connector named <platform>-playwright.js will automatically reuse this session.
`);
}

// ─── Generate Login Connector ───────────────────────────────
function generateLoginConnector(platform, loginUrl, timeout, checkUrl) {
  const maxPolls = Math.floor(timeout / 2);
  const loginHostname = new URL(loginUrl).hostname;

  const lines = [];
  lines.push('/**');
  lines.push(' * Session Capture — ' + platform);
  lines.push(' * Auto-generated by capture-session.cjs');
  lines.push(' */');
  lines.push('');
  lines.push('(async () => {');
  lines.push('  const loginUrl = ' + JSON.stringify(loginUrl) + ';');
  lines.push('  const loginHostname = ' + JSON.stringify(loginHostname) + ';');
  lines.push('  const maxPolls = ' + maxPolls + ';');
  lines.push('');
  lines.push('  // Record initial state');
  lines.push('  await page.sleep(3000);');
  lines.push('  var initialUrl = \'\';');
  lines.push('  var initialCookieCount = 0;');
  lines.push('  try {');
  lines.push('    initialUrl = await page.evaluate(\'window.location.href\');');
  lines.push('    initialCookieCount = await page.evaluate(\'document.cookie.split(\";\").filter(function(c) { return c.trim(); }).length\');');
  lines.push('  } catch(e) {');
  lines.push('    // Page may be redirecting, use defaults');
  lines.push('  }');
  lines.push('');
  lines.push('  await page.setData(\'status\', \'Please log in to ' + platform + ' in the browser window. Session will be captured automatically.\');');
  lines.push('');
  lines.push('  // Poll for login completion');
  lines.push('  var loggedIn = false;');
  lines.push('  for (var i = 0; i < maxPolls; i++) {');
  lines.push('    await page.sleep(2000);');
  lines.push('');
  lines.push('    // Wrap in try/catch — page.evaluate throws if user is navigating');
  lines.push('    var currentUrl, currentCookieCount;');
  lines.push('    try {');
  lines.push('      currentUrl = await page.evaluate(\'window.location.href\');');
  lines.push('    } catch(e) {');
  lines.push('      // Navigation in progress, skip this poll');
  lines.push('      continue;');
  lines.push('    }');
  lines.push('    try {');
  lines.push('      currentCookieCount = await page.evaluate(\'document.cookie.split(\";\").filter(function(c) { return c.trim(); }).length\');');
  lines.push('    } catch(e) {');
  lines.push('      currentCookieCount = 0;');
  lines.push('    }');
  lines.push('');
  lines.push('    // Check if URL changed significantly from login page');
  lines.push('    var onLoginPage = currentUrl.includes(\'/login\') || currentUrl.includes(\'/signin\') || currentUrl.includes(\'/auth\') || currentUrl.includes(\'/challenge\') || currentUrl.includes(\'/identifier\') || currentUrl.includes(\'/pwd\') || currentUrl.includes(\'/v2/\');');
  lines.push('    var urlChanged = currentUrl !== initialUrl && !onLoginPage;');
  lines.push('');
  lines.push('    // Check if cookies increased (session established)');
  lines.push('    var cookiesIncreased = currentCookieCount > initialCookieCount + 1;');
  lines.push('');

  if (checkUrl) {
    lines.push('    // Check for specific success URL');
    lines.push('    if (currentUrl.includes(' + JSON.stringify(checkUrl) + ')) {');
    lines.push('      loggedIn = true;');
    lines.push('      break;');
    lines.push('    }');
    lines.push('');
  }

  lines.push('    if (urlChanged && cookiesIncreased) {');
  lines.push('      await page.setData(\'status\', \'Login detected! Waiting for session to settle...\');');
  lines.push('      await page.sleep(3000);');
  lines.push('      loggedIn = true;');
  lines.push('      break;');
  lines.push('    }');
  lines.push('');
  lines.push('    // Also detect: URL changed to completely different hostname');
  lines.push('    try {');
  lines.push('      var currentHost = new URL(currentUrl).hostname;');
  lines.push('      if (currentHost !== loginHostname && !onLoginPage) {');
  lines.push('        await page.setData(\'status\', \'Login detected (redirected to \' + currentHost + \')! Waiting for session to settle...\');');
  lines.push('        await page.sleep(3000);');
  lines.push('        loggedIn = true;');
  lines.push('        break;');
  lines.push('      }');
  lines.push('    } catch(e) {}');
  lines.push('');
  lines.push('    // Progress update');
  lines.push('    if (i > 0 && i % 5 === 0) {');
  lines.push('      var remaining = Math.floor((maxPolls - i) * 2);');
  lines.push('      await page.setData(\'status\', \'Waiting for login... (\' + remaining + \'s remaining). Current URL: \' + currentUrl.substring(0, 80));');
  lines.push('    }');
  lines.push('  }');
  lines.push('');
  lines.push('  if (!loggedIn) {');
  lines.push('    await page.setData(\'error\', \'Login timeout after ' + timeout + 's. Try again with --timeout <seconds> for more time, or --check-url <pattern> to specify a success indicator.\');');
  lines.push('    return;');
  lines.push('  }');
  lines.push('');
  lines.push('  await page.setData(\'status\', \'Capturing session data...\');');
  lines.push('');
  lines.push('  // Capture browser-accessible session data');
  lines.push('  // Wait for page to settle after login');
  lines.push('  await page.sleep(2000);');
  lines.push('  var cookieStr = \'\';');
  lines.push('  var finalUrl = \'\';');
  lines.push('  var localStorageData = {};');
  lines.push('  var sessionStorageData = {};');
  lines.push('  try {');
  lines.push('    cookieStr = await page.evaluate(\'document.cookie\');');
  lines.push('    finalUrl = await page.evaluate(\'window.location.href\');');
  lines.push('  } catch(e) { /* page still settling */ }');
  lines.push('  try {');
  lines.push('    localStorageData = await page.evaluate(\'(function() { var d = {}; for (var i = 0; i < localStorage.length; i++) { var k = localStorage.key(i); try { d[k] = localStorage.getItem(k); } catch(e) {} } return d; })()\') || {};');
  lines.push('  } catch(e) {}');
  lines.push('  try {');
  lines.push('    sessionStorageData = await page.evaluate(\'(function() { var d = {}; for (var i = 0; i < sessionStorage.length; i++) { var k = sessionStorage.key(i); try { d[k] = sessionStorage.getItem(k); } catch(e) {} } return d; })()\') || {};');
  lines.push('  } catch(e) {}');
  lines.push('');
  lines.push('  // Parse cookies');
  lines.push('  var cookies = cookieStr ? cookieStr.split(\';\').map(function(c) {');
  lines.push('    var parts = c.trim().split(\'=\');');
  lines.push('    return { name: parts[0], value: parts.slice(1).join(\'=\') };');
  lines.push('  }).filter(function(c) { return c.name; }) : [];');
  lines.push('');
  lines.push('  var result = {');
  lines.push('    platform: ' + JSON.stringify(platform) + ',');
  lines.push('    capturedAt: new Date().toISOString(),');
  lines.push('    loginUrl: ' + JSON.stringify(loginUrl) + ',');
  lines.push('    finalUrl: finalUrl,');
  lines.push('    cookies: cookies,');
  lines.push('    localStorage: localStorageData || {},');
  lines.push('    sessionStorage: sessionStorageData || {},');
  lines.push('    stats: {');
  lines.push('      cookieCount: cookies.length,');
  lines.push('      localStorageKeys: Object.keys(localStorageData || {}).length,');
  lines.push('      sessionStorageKeys: Object.keys(sessionStorageData || {}).length');
  lines.push('    },');
  lines.push('    note: \'Full session (including HttpOnly cookies) is persisted in the browser profile. This file contains browser-accessible data only.\',');
  lines.push('    profileDir: \'~/.dataconnect/browser-profiles/' + platform + '-playwright/\'');
  lines.push('  };');
  lines.push('');
  lines.push('  await page.setData(\'result\', result);');
  lines.push('  await page.setData(\'status\', \'Session captured! \' + cookies.length + \' cookies, \' + Object.keys(localStorageData || {}).length + \' localStorage items.\');');
  lines.push('})();');

  return lines.join('\n');
}

// ─── Main ───────────────────────────────────────────────────
async function main() {
  const args = parseArgs();
  const runnerDir = resolveRunnerDir();

  // Create sessions directory
  const sessionsDir = path.join(__dirname, 'sessions');
  if (!fs.existsSync(sessionsDir)) {
    fs.mkdirSync(sessionsDir, { recursive: true });
  }

  // Generate temporary connector files
  // IMPORTANT: Use <platform>-playwright as filename so the browser profile
  // matches what real connectors will use (profile name = basename without .js)
  const connectorName = `${args.platform}-playwright`;
  const connectorPath = path.join(sessionsDir, `${connectorName}.js`);
  const metadataPath = path.join(sessionsDir, `${connectorName}.json`);

  const connectorCode = generateLoginConnector(
    args.platform,
    args.loginUrl,
    args.timeout,
    args.checkUrl
  );

  const metadata = {
    name: connectorName,
    description: `Session capture for ${args.platform}`,
    version: '0.0.0',
    connectURL: args.loginUrl,
    scopes: [],
  };

  fs.writeFileSync(connectorPath, connectorCode);
  fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));

  console.log('');
  console.log(`${c.bold}Session Capture${c.reset}`);
  console.log('─'.repeat(50));
  console.log(`  ${c.cyan}Platform:${c.reset}  ${args.platform}`);
  console.log(`  ${c.cyan}Login URL:${c.reset} ${args.loginUrl}`);
  console.log(`  ${c.cyan}Timeout:${c.reset}   ${args.timeout}s`);
  console.log(`  ${c.cyan}Profile:${c.reset}   ~/.dataconnect/browser-profiles/${connectorName}/`);
  console.log('─'.repeat(50));
  console.log('');
  console.log(`${c.yellow}A browser window will open. Please log in manually.${c.reset}`);
  console.log(`${c.dim}Login is detected automatically via URL change + cookie increase.${c.reset}`);
  console.log('');

  const startTime = Date.now();
  const resultRef = { data: null };

  // Spawn the playwright runner
  const child = spawn('node', ['index.cjs'], {
    cwd: runnerDir,
    stdio: ['pipe', 'pipe', 'pipe'],
  });

  // Handle stdout (JSON protocol)
  const stdoutRL = readline.createInterface({ input: child.stdout });
  stdoutRL.on('line', (line) => {
    try {
      const msg = JSON.parse(line);

      if (msg.type === 'ready') {
        const runCmd = JSON.stringify({
          type: 'run',
          runId: `session-${Date.now()}`,
          connectorPath: path.resolve(connectorPath),
          url: args.loginUrl,
          headless: false,
          forceHeaded: true,
        });
        child.stdin.write(runCmd + '\n');
        print(c.green, '[capture]', 'Browser opening — please log in...');
        return;
      }

      if (msg.type === 'result' && msg.data) {
        resultRef.data = msg.data;
      } else if (msg.type === 'status') {
        const statusStr = typeof msg.status === 'string'
          ? msg.status
          : (msg.status && msg.status.message) || JSON.stringify(msg.status);
        print(c.blue, '[status]', statusStr);
      } else if (msg.type === 'data') {
        if (msg.key === 'result') {
          // page.setData('result', ...) arrives as a data event
          resultRef.data = msg.value;
        } else if (msg.key === 'error') {
          print(c.red, '[error]', String(msg.value));
        } else if (msg.key === 'status') {
          print(c.blue, '[status]', String(msg.value));
        }
      } else if (msg.type === 'error') {
        print(c.red, '[error]', msg.message || JSON.stringify(msg));
      } else if (msg.type === 'log') {
        print(c.gray, '[log]   ', msg.message || '');
      }
    } catch (e) {
      if (line.trim()) {
        console.log(`${c.dim}${line}${c.reset}`);
      }
    }
  });

  // Handle stderr
  const stderrRL = readline.createInterface({ input: child.stderr });
  stderrRL.on('line', (line) => {
    if (line.trim()) {
      print(c.dim, '[runner]', line.replace('[PlaywrightRunner] ', ''));
    }
  });

  // Wait for process to exit (small delay to ensure stdout is fully flushed)
  const exitCode = await new Promise((resolve) => {
    child.on('exit', (code) => {
      setTimeout(() => resolve(code || 0), 500);
    });
  });

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  // Clean up temporary connector files
  try { fs.unlinkSync(connectorPath); } catch (e) { /* ignore */ }
  try { fs.unlinkSync(metadataPath); } catch (e) { /* ignore */ }

  console.log('');
  console.log('─'.repeat(50));

  // Save session data
  if (resultRef.data) {
    const sessionFile = path.join(sessionsDir, `${args.platform}.json`);
    fs.writeFileSync(sessionFile, JSON.stringify(resultRef.data, null, 2));
    print(c.green, '[saved]', `Session data: ${sessionFile}`);
    print(c.green, '[saved]', `Browser profile: ~/.dataconnect/browser-profiles/${connectorName}/`);

    const stats = resultRef.data.stats || {};
    console.log('');
    console.log(`${c.bold}${c.green}Session captured successfully!${c.reset} (${elapsed}s)`);
    console.log(`  ${c.cyan}Cookies:${c.reset}        ${stats.cookieCount || 0}`);
    console.log(`  ${c.cyan}localStorage:${c.reset}   ${stats.localStorageKeys || 0} keys`);
    console.log(`  ${c.cyan}sessionStorage:${c.reset} ${stats.sessionStorageKeys || 0} keys`);
    console.log(`  ${c.cyan}Final URL:${c.reset}      ${resultRef.data.finalUrl || 'unknown'}`);
    console.log('');
    console.log(`${c.dim}The session is persisted in the browser profile.${c.reset}`);
    console.log(`${c.dim}Any connector named ${connectorName}.js will automatically reuse it.${c.reset}`);
  } else {
    console.log(`${c.bold}${c.red}Session capture failed.${c.reset} (${elapsed}s)`);
    console.log(`${c.dim}No session data was returned. Check error messages above.${c.reset}`);
  }
  console.log('');

  process.exit(exitCode);
}

main().catch((err) => {
  console.error(`${c.red}Fatal error: ${err.message}${c.reset}`);
  process.exit(1);
});
